# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Whatsthat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Whatsthat

pod 'MBProgressHUD', '~> 1.1.0'
pod 'TwitterKit'

end
